### ISSUE TITLE
注册stripe验证完公司信息后需要SSN

### ISSUE THREAD

**Issue by john-dududu** [hua1995116/indiehackers-steps#12]
注册stripe验证完公司信息后，需要添加公司代表的个人信息 ，这里需要验证SSN，
问了客服必须是要SSN，如果不验证个人代表信息，会暂停公司付款收款

有人知道吗

**Comment by huangfengye** [comment]
itin可以吗？

**Comment by john-dududu** [comment]
更新一下 在填写SSN的地方直接写EIN后四位就可以了， 问客服还说只能用SSN
