### ISSUE TITLE
求怎么办：stripe 上要求香港身份证号

### ISSUE THREAD

**Issue by iphysresearch** [hua1995116/indiehackers-steps#3]
![WX20231228-114929@2x](https://github.com/hua1995116/indiehackers-steps/assets/14322948/321f3010-88d4-4841-8a40-df7c4d008190)

我是从medium上开的账户，整了美国公司啥EIN的，但是现在补全信息才能收款，不知道这下怎么办了。。。

**Comment by solo-xwz** [comment]
为什么要香港的？你填了什么香港的信息？

**Comment by iphysresearch** [comment]
> 为什么要香港的？你填了什么香港的信息？

已解决，把HK换成CN，就可以写大陆的身份证号码了哈。
